title: environment
oneOf:
  - type: string
    description: "Environment name"
  - type: object
    properties:
      name:
        type: string
      sequential:
        type: boolean
      items:
        type: array
        items:
          type: object
          properties:
            name:
              type: string
            deploy-to:
              oneOf:
                - type: string
                  enum: [all]
                - type: array
                  items:
                    type: string
"$schema": http://json-schema.org/draft-07/schema#
