title: FailureStrategyActionConfig
type: object
required:
- type
discriminator: type
properties:
  type:
    type: string
    enum:
    - Ignore
    - Retry
    - MarkAsSuccess
    - Abort
    - StageRollback
    - StepGroupRollback
    - PipelineRollback
    - ManualIntervention
    - ProceedWithDefaultValues
    - MarkAsFailure
  description:
    desc: This is the description for FailureStrategyActionConfig
$schema: http://json-schema.org/draft-07/schema#
