title: ManualInterventionFailureActionConfig
type: object
properties:
  type:
    type: string
    enum:
      - ManualIntervention
  spec:
    type: object
    required:
      - timeout
    properties:
      timeout:
        type: string
        minLength: 1
        pattern: ^[1-9]\d*[smhdw](\s+[1-9]\d*[smhdw])*$
        description: "Duration string e.g. '10s', '30m', '2h'"
      onTimeout:
        properties:
          action:
            description: "Action to take. Recommended types: Abort, Ignore, MarkAsSuccess, MarkAsFailure"
$schema: http://json-schema.org/draft-07/schema#
