title: DRTestStageConfigImpl
type: object
required:
- execution
properties:
  execution:
    $ref: execution-element-config.yaml
  description:
    desc: This is the description for DRTestStageConfigImpl
$schema: http://json-schema.org/draft-07/schema#
