pipeline_stages:
  - "stages/iacm/iacmstage-node.yaml"
  - "stages/cd/deployment-stage-node.yaml"
  - "stages/security/security-stage-node.yaml"
  - "stages/ci/integration-stage-node.yaml"
  - "stages/approval/approval-stage-node.yaml"
  - "stages/custom/pipeline-stage-node.yaml"
  - "stages/custom/dynamic-stage-node.yaml"
  - "stages/custom/custom-stage-node.yaml"
  - "stages/cf/feature-flag-stage-node.yaml"
  - "stages/template/template-stage-node.yaml"
  - "stages/idp/idpstage-node.yaml"
  - "stages/drtest/drteststage-node.yaml"