title: EnvironmentItem
description: Single environment item configuration.
type: object
required:
  - id
properties:
  id:
    description: Environment identifier.
    type: string
  ref:
    description: Git branch for the environment configuration.
    type: string
oneOf:
  # With deploy-to
  - required:
      - deploy-to
    properties:
      deploy-to:
        description: Infrastructure(s) to deploy to.
        $ref: ./deploy-to.yaml
  # With filters
  - required:
      - filters
    properties:
      filters:
        description: Filters for selecting infrastructures.
        $ref: ./filters.yaml
additionalProperties: false
$schema: http://json-schema.org/draft-07/schema#
