title: EnvironmentGroup
description: Environment group configuration.
type: object
required:
  - id
properties:
  id:
    description: Environment group identifier.
    type: string
  items:
    description: List of environments from the group.
    type: array
    items:
      $ref: ./environment-item.yaml
additionalProperties: false
$schema: http://json-schema.org/draft-07/schema#
