title: ConfigMapVolumeYamlSpecV1
description: ConfigMap volume specification.
type: object
required:
  - mount-path
  - name
properties:
  mount-path:
    description: Mount path in the container. Supports expressions.
    type: string
  name:
    description: Name of the ConfigMap. Supports expressions.
    type: string
  optional:
    description: Whether the ConfigMap must exist. Supports expressions.
    oneOf:
      - type: boolean
      - type: string
        pattern: "(\\$\\{\\{.+\\}\\}|<\\+.+>.*)"
$schema: http://json-schema.org/draft-07/schema#

