title: FmeFlagSetDynamicConfigurationsStepInfo
allOf:
  - $ref: ../../common/step-spec-type.yaml
  - type: object
    required:
      - flagName
      - environment
      - treatments
    properties:
      flagName:
        oneOf:
          - $ref: ../common/fme-flag-common-flag-name.yaml
          - $ref: ../common/common-jexl.yaml
      environment:
        oneOf:
          - $ref: ../common/fme-flag-common-environment.yaml
          - $ref: ../common/common-jexl.yaml
      treatments:
        description: "List of treatments with their configurations"
        oneOf:
          - type: array
            items:
              type: object
              required:
                - treatment
                - configuration
              properties:
                treatment:
                  oneOf:
                    - $ref: ../common/fme-flag-common-treatment.yaml
                    - $ref: ../common/common-jexl-expression-only.yaml
                configuration:
                  type: string
          - $ref: ../common/common-jexl.yaml
      inputVariables:
        type: array
        items:
          oneOf:
            - $ref: ../../common/number-ng-variable.yaml
            - $ref: ../../common/secret-ng-variable.yaml
            - $ref: ../../common/string-ng-variable.yaml
$schema: http://json-schema.org/draft-07/schema#
