title: PolicyConfig
description: Policy enforcement configuration.
type: object
properties:
  policySets:
    description: Policy sets to enforce.
    type: array
    items:
      type: string
$schema: http://json-schema.org/draft-07/schema#

