title: OnFailureConfig
type: object
required:
- action
- errors
properties:
  action:
    $ref: failure-strategy-action-config.yaml
  errors:
    type: array
    items:
      type: string
      enum:
      - Unknown
      - AllErrors
      - Authentication
      - Connectivity
      - Timeout
      - Authorization
      - Verification
      - DelegateProvisioning
      - PolicyEvaluationFailure
      - InputTimeoutError
      - ApprovalRejection
      - DelegateRestart
  description:
    desc: This is the description for OnFailureConfig
$schema: http://json-schema.org/draft-07/schema#
