type: object
title: executionConfig
required:
  - steps
properties:
  rollbackSteps:
    type: array
    items:
      "$ref": "./execution_element.yaml"
  steps:
    type: array
    items:
      "$ref": "./execution_element.yaml"
    maxItems: 2147483647
    minItems: 1
"$schema": http://json-schema.org/draft-07/schema#
