steps:
  - ../../common/step-element-config.yaml
  - ../../steps/common/background-step-node.yaml
  - ../../steps/cd/terraform-apply-step-node.yaml
  - ../../steps/cd/terraform-plan-step-node.yaml
  - ../../steps/cd/terraform-destroy-step-node.yaml
  - ../../steps/cd/terraform-rollback-step-node.yaml
  - ../../steps/cd/cloudformation-create-stack-step-node.yaml
  - ../../steps/cd/cloudformation-delete-stack-step-node.yaml
  - ../../steps/cd/cloudformation-rollback-step-node.yaml
  - ../../steps/cd/azure-create-a-r-m-resource-step-node.yaml
  - ../../steps/cd/azure-create-b-p-step-node.yaml
  - ../../steps/cd/azure-a-r-m-rollback-step-node.yaml
  - ../../steps/cd/jenkins-build-step-node.yaml
  - ../../steps/cd/shell-script-provision-step-node.yaml
  - ../../steps/cd/chaos-step-node.yaml
  - ../../steps/cd/ai-test-automation-step-node.yaml
  - ../../steps/cd/terragrunt-plan-step-node.yaml
  - ../../steps/cd/terragrunt-apply-step-node.yaml
  - ../../steps/cd/terragrunt-destroy-step-node.yaml
  - ../../steps/cd/terragrunt-rollback-step-node.yaml
  - ../../steps/cd/asg-canary-deploy-step-node.yaml
  - ../../steps/cd/asg-canary-delete-step-node.yaml
  - ../../steps/cd/asg-rolling-deploy-step-node.yaml
  - ../../steps/cd/asg-rolling-rollback-step-node.yaml
  - ../../steps/cd/asg-blue-green-deploy-step-node.yaml
  - ../../steps/cd/asg-blue-green-rollback-step-node.yaml
  - ../../steps/cd/asg-blue-green-swap-service-step-node.yaml
  - ../../steps/cd/terraform-cloud-run-step-node.yaml
  - ../../steps/cd/aws-lambda-deploy-step-node.yaml
  - ../../steps/cd/aws-sam-deploy-step-node.yaml
  - ../../steps/cd/download-manifests-step-node.yaml
  - ../../steps/cd/aws-sam-build-step-node.yaml
  - ../../steps/cd/aws-sam-rollback-step-node.yaml
  - ../../steps/cd/terraform-cloud-rollback-step-node.yaml
  - ../../steps/cd/aws-lambda-rollback-step-node.yaml
  - ../../steps/cd/bamboo-build-step-node.yaml
  - ../../steps/custom/http-step-node.yaml
  - ../../steps/custom/email-step-node.yaml
  - ../../steps/custom/queue-step-node.yaml
  - ../../steps/custom/shell-script-step-node.yaml
  - ../../steps/custom/custom-approval-step-node.yaml
  - ../../steps/custom/jira-create-step-node.yaml
  - ../../steps/custom/jira-update-step-node.yaml
  - ../../steps/common/template-step-node.yaml
  - ../../steps/custom/service-now-approval-step-node.yaml
  - ../../steps/custom/jira-approval-step-node.yaml
  - ../../steps/custom/harness-approval-step-node.yaml
  - ../../steps/custom/barrier-step-node.yaml
  - ../../steps/custom/service-now-create-step-node.yaml
  - ../../steps/custom/service-now-update-step-node.yaml
  - ../../steps/custom/service-now-import-set-step-node.yaml
  - ../../steps/custom/flag-configuration-step-node.yaml
  - ../../steps/custom/policy-step-node.yaml
  - ../../steps/custom/wait-step-node.yaml
  - ../../steps/custom/container-step-node.yaml
  - ../../steps/common/run-step-node.yaml
  - ../../steps/common/plugin-step-node.yaml
  - ../../steps/common/action-step-node.yaml
  - ../../steps/cd/serverless-aws-lambda-deploy-v2-step-node.yaml
  - ../../steps/cd/serverless-aws-lambda-package-v2-step-node.yaml
  - ../../steps/cd/serverless-aws-lambda-prepare-rollback-v2-step-node.yaml
  - ../../steps/cd/serverless-aws-lambda-rollback-v2-step-node.yaml
  - ../../steps/common/aws-cdk-bootstrap-step-node.yaml
  - ../../steps/common/aws-cdk-synth-step-node.yaml
  - ../../steps/common/aws-cdk-diff-step-node.yaml
  - ../../steps/common/aws-cdk-deploy-step-node.yaml
  - ../../steps/common/dbops-apply-schema-step-node.yaml
  - ../../steps/common/dbops-rollback-schema-step-node.yaml
  - ../../steps/common/aws-cdk-destroy-step-node.yaml
  - ../../steps/custom/step-group-node.yaml
  - ../../steps/custom/parallel-node.yaml
  - ../../steps/cd/download-aws-s3-step-node.yaml
  - ../../steps/cd/download-harness-store-step-node.yaml
