title: ManualFailureSpecConfigV1
type: object
description: Manual intervention configuration for failure strategy.
properties:
  timeout:
    description: Timeout for manual intervention. Supports expressions.
    type: string
  timeout-action:
    description: Action to take when timeout is reached.
    $ref: ./failure-strategy-action-config.yaml
  available-actions:
    description: List of available actions for manual intervention.
    type: array
    items:
      $ref: ./failure-strategy-action-config.yaml
$schema: http://json-schema.org/draft-07/schema#

