title: FailureConfigV1
type: object
description: Failure strategy configuration for handling errors.
required:
  - errors
  - action
properties:
  errors:
    description: List of error types to handle. Supports single value or array. Supports expressions.
    oneOf:
      - type: array
        items:
          $ref: ./ng-failure-type.yaml
      - $ref: ./ng-failure-type.yaml
  action:
    $ref: ./failure-strategy-action-config.yaml
$schema: http://json-schema.org/draft-07/schema#
