title: RetryFailureSpecConfigV1
type: object
description: Retry configuration for failure strategy.
properties:
  attempts:
    description: Number of retry attempts. Supports expressions.
    oneOf:
      - type: integer
        minimum: 1
      - type: string
        pattern: "(\\$\\{\\{.+\\}\\}|<\\+.+>.*)"
  interval:
    description: Interval between retries. Can be single value or array of timeouts. Supports expressions.
    oneOf:
      - type: array
        items:
          type: string
      - type: string
  failure-action:
    description: Action to take after all retries are exhausted.
    $ref: ./failure-strategy-action-config.yaml
$schema: http://json-schema.org/draft-07/schema#

