title: RetryStepGroupFailureSpecConfigV1
type: object
description: Retry step group configuration for failure strategy.
properties:
  attempts:
    description: Number of retry attempts. Supports expressions.
    oneOf:
      - type: integer
        minimum: 1
      - type: string
        pattern: "(\\$\\{\\{.+\\}\\}|<\\+.+>.*)"
  interval:
    description: Interval between retries. Can be single value or array of timeouts. Supports expressions.
    oneOf:
      - type: array
        items:
          type: string
      - type: string
$schema: http://json-schema.org/draft-07/schema#

